// FLAT ACTIONS
export const FLAT_ACTIONS = {
  VIEW_ALL_FLATS: {
    REQUEST: 'REQUEST',
    RESPONSE: 'RESPONSE',
    FAILED: 'FAILED'
  },

  VIEW_FLAT: 'VIEW_FLAT',
  ADD_FLAT: 'ADD_FLAT',
  EDIT_FLAT: 'EDIT_FLAT',
  DELETE_FLAT: 'DELETE_FLAT'
};

// Login Actions
export const LOGIN_ACTIONS = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_RESPONSE: 'LOGIN_RESPONSE',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOADER: {
    LOGIN_ENABLE_LOADER: 'LOGIN_ENABLE_LOADER',
    LOGIN_DISABLE_LOADER: 'LOGIN_DISABLE_LOADER'
  }
};

// Favorite flat
export const FAVOURITE_FLAT = {
  ADD_FLAT_TO_FAVORITE: 'ADD_FLAT_TO_FAVORITE',
  REMOVE_FLAT_FROM_FAVORITE: 'REMOVE_FLAT_FROM_FAVORITE'
};
